# Source language and JDK version to use
language: java
jdk: oraclejdk7

# Compile and package JAR and set build properties
install: mvn package -DbuildNumber=$TRAVIS_BUILD_NUMBER -Dci=travis -Dcommit=${TRAVIS_COMMIT:0:7}

# Perform steps after compilation/test success
after_success:
  # Generate Javadocs and Cobertura report for Coveralls.io
  - "mvn javadoc:javadoc cobertura:cobertura coveralls:cobertura -DserviceJobId=$TRAVIS_JOB_ID"
  # Get files for use with build, namely the custom Maven settings.xml
  - "git clone https://github.com/flow/travis-ci-resources.git target/travis"
  # Check if commit is not a pull request, if git repo is official, and if branch is master, then deploy artifacts to Maven repository
  - "[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_REPO_SLUG == flow/flow-filesystem ]] && [[ $TRAVIS_BRANCH == master ]] && mvn deploy --settings target/travis/settings.xml"

# Notification services
notifications:
  # Disable build status email notifications, until the issue with forks is fixed
  email: false
  webhooks:
    # Send build information and status to Notifico
    - http://n.tkte.ch/h/1816/foGmQacrp10wM3mk6AfYnT60

# Environmental system variables
env:
  global:
    # Make the log output cleaner
    - TERM=dumb
    # Super secure, encrypted variables! Ssssh!
    - secure: "ichBn4dddjKY7/ac5BsfND5pYUSOSLKhd81kwdgrwym8RygMjErp9vm9evaZFvrsxWuXk7HQWiJIKYiRGj64hG2dSE8bzFK/1F9D+x5ks7VBL4tCzhe0K5gQSjYkuUApud2cwjEMmbmeVn8gBqVZnLp99D+XJZCSFGd3nSKbPiE="
    - secure: "RK0FDhSghkMIRQRrVCJSHj0tj7m1q/Dcu6q8xhBr36WWvFHJyvVOg7xywLFmsMkzU+ylDnYbLlExi3z6lw5apm0fOm+8rsKpRM71DaIP1rXd3CfQavZiiFI/alrwwExgYe05dWjkEiEgQ/7lx0sJoE2QQy0Nyaehc8TtF0VC8hM="
